.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. bikcoin_qt test_bikcoin_qt
clean: FORCE
	$(MAKE) -C .. bikcoin_qt_clean test_bikcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_bikcoin_qt_check
bikcoin-qt bikcoin-qt.exe: FORCE
	 $(MAKE) -C .. bikcoin_qt
